{% set name = "parse" %}
{% set version = "1.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b41d604d16503c79d81af5165155c0b20f6c8d6c559efa66b4b695c3e5a0a0ce

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=61.2
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - parse
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/r1chardj0n3s/parse
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: parse() is the opposite of format()
  description: |
    Parse strings using a specification based on the Python format() syntax.
  doc_url: https://github.com/r1chardj0n3s/parse/blob/master/README.rst
  dev_url: https://github.com/r1chardj0n3s/parse

extra:
  recipe-maintainers:
    - stuertz
