travis:
  secure:
    BINSTAR_TOKEN: QRqKcbcBDKWK9pA+VZYo9Tzas3YA4Zk/jpw7Fm8g4fS3rCIBFK4uhOxsxWFrgOcJWhuXeiXywf/mygtA4fRsoBDc7UYv/ouxh26Mix+8LGx2yJ9k6xM4qfMXmfUyY0IipDYUZqzHOCs6wRk6cTpjPdXr08UwqvO8d7BduZi2WIsQB42STshfWIA1BXzbmUyhpTN9SSZV2eIMk6Ji9IA2STVmS6efZbiWcbbK4yig367HfUOSOzy4GI60eF9KWLh9rhPnatOnKeoqCbVZV9L7JUGIWczRr16/cQ39R40enhg+dx7QPgw+QK6Qdn92BBVZCJ3zyrVTUSV7VYwS2FnoSDJXhH500+Hr3jXBO7miky4AtOGcNsZY+BvRw6yv5POmOdWQ6FWFwe+dfJlcDugYcPDyb2qHEL1qrVyTa6zgoymgFnL1Pswz2S+A+1gyOb3iGvlrFtJPQWb+aZ5VPvD5LxawwmD2uhyvoUAlzDkWRIzg2IUeUQNZrKscB3R5iyIUCH01tMLpHyYdf3Oe+t5PzNzr0dcvMJTJJkaYfyHDXYPklLkWbtOg7K/K0CF+aM/BoAjCeRgXrlpwIR2qCMTBMe68ePhSO74QLriGzMqemOI4gV54/vcQHzzrQDdcd7VBPpU1DqjKG+JcSxqA90516zmw7b0MyoSwfm52PFuLh0g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
