travis:
  secure:
    BINSTAR_TOKEN: lKRilUadGkmGA+oSCd3EKnvz2ZBT+StH9vG9cPfSfylibNMpfYFbi01lOUVC3Ie/qlio4OMW6K5E+12WVLkBSzC0OJNFFPLRekX8Q1KkxKS9rhksUpXyjCYZqGWhr/zFkbyYwFYlyvva0+R2oGvMu15KqEWIl0kvUgWQ3WYp+oywdTiz6ZWldfxBm5Z6k7w+ddKP8a1W/q/ePDgNNULCgDU3s4Buei9QNR5q5YhjcaeVoaJLVZQaNtb1GxMgx628n5y6GaED4VO4tfky+SJWReMHNAQ4LEcLGCB3sOUoE0/0rzikBzyqEnK8j5O3iWqAzT4n5tUzOoU8HPFLVp+w6A3BsQjl1u0VX4Hgd2eE0NvpCkuoHSvGJiu5gzC1CjV+Nfwo3/YyZbFGXvZsAcU9neNdnLgrn2+TsPgNHUbdeORAgGYxXP1W/5ro0OpXLYT2o2UVXxiaoTbjHFO+p8M4lPiCu4U+HvHX1qZCmesz4MAnaJMmAjX/3ucGcEDpEas02aRxEnCSWTpvdAe2cyBo4eq3ncksCZD7ebE7rzehp7OC7SNmRtelX1lWmx/vjkjtlvN/a8dUtr7C9qewiqd6fJi8bdy/5EgERQ7nOiIj/rQmIgZOiYguPQs9I5TxloZE36h6XFpNfJnDtyGhVFFKTjo3IN+vgJpOsUA+AMXUB7U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
